= Security Policy

== Supported Versions

////
Use this section to tell people about which versions of your project are
currently being supported with security updates.

| Version | Supported          |
| ------- | ------------------ |
| 5.1.x   | :white_check_mark: |
| 5.0.x   | :x:                |
| 4.0.x   | :white_check_mark: |
| < 4.0   | :x:                |
////

This project releases the utility under a rolling release model: as soon as updates are considered ready for end-user consumption, they are made available to users. Therefore, security vulnerabilities are only considered important if they are present in the utility in the way it is made available to end users.

== Reporting a Vulnerability

////
Use this section to tell people how to report a vulnerability.

Tell them where to go, how often they can expect to get an update on a
reported vulnerability, what to expect if the vulnerability is accepted or
declined, etc.
////

To report a security vulnerability, please follow the instructions at https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability[].
